### ISSUE TITLE
gulp-sass v2.3.2 (libsass?) incompatibility

### ISSUE THREAD

**Issue by miduku** [jhildenbiddle/vertical-rhythm-reset#1]
Tested your SCSS using **gulp-sass v2.3.2** and it stopped my gulp task.
It didn't throw me an error, it just stopped.

Then tested it in http://www.sassmeister.com/, selected LibSass v3.3.6 and it didn't compile it as well. 

Testing it further with Sass v3.3.14 it gave me the Error "Functions can only contain variable declarations and control directives.".

It works with regular **ruby sass v3.4.22** (I installed **gulp-ruby-sass v2.1.0**).
I'm not sure what the problem is and couldn't narrow it down but I'm assuming that how some functions were written could be the cause.

Maybe add a heads up in the readme before the problem is solved and so than others don't have to spend many hours finding out what the problem is.

**Comment by jhildenbiddle** [comment]
Thanks for taking the time to report the issue, @miduku. Very much appreciated.

I've addressed the issue that was causing LibSass to fail. The failure was caused by the string concatenation method I was using to generate the grid overlay lines and text. I've verified the fix using LibSass v3.3.6 on [sassmeister.com](http://www.sassmeister.com/).

I've also updated the [documentation](https://github.com/jhildenbiddle/vertical-rhythm-reset/blob/master/README.md) to include compiler requirements per your suggestion.

Hope this helps and addresses the issues you were having.
